(function (_$cont) {
  (function (_$cont) {
    try {
      setTimeout(function (arguments) {
        try {
          throw new Error('my error');
          _$cont();
        } catch (_$err) {
          _$cont(_$err);
        }
      }.bind(this, arguments), 20);
    } catch (_$err) {
      _$cont(_$err);
    }
  }(function (err) {
    if (err !== undefined) {
      console.log('Error caught:');
      setTimeout(function (arguments) {
        console.log(err);
        _$cont();
      }.bind(this, arguments), 10);
    } else
      _$cont();
  }));
}(function () {
  console.log('Finally');
  console.log('Done');
}));
/* Generated by Continuation.js v0.1.7 */