(function (_$cont) {
  try {
    throw new Error('my error');
  } catch (err) {
    setTimeout(function (arguments) {
      console.log(err);
      _$cont();
    }.bind(this, arguments), 10);
    return;
  }
  _$cont();
}(function () {
  console.log('Done');
}));
/* Generated by Continuation.js v0.1.7 */